version: '3'
services:
  backend:
    build: ./backend
    container_name: art-photo_backend_1
    environment:
      - CONFIG_PATH=configure.ini
      - FLASK_APP=main.py
      # для отладки (при запуске в релиз убрать!)
      - PYTHONUNBUFFERED=True     # Позволяет отслеживать процесс работы приложения в командной строке
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0
    restart: always
